# Generated by Django 6.0.1 on 2026-01-13 03:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('status', models.IntegerField(choices=[(1, '待付款'), (2, '待发货'), (3, '待收货'), (4, '已完成'), (5, '已取消')], default=1, verbose_name='订单状态')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总金额')),
                ('freight_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='运费')),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实付金额')),
                ('receiver_name', models.CharField(max_length=50, verbose_name='收货人')),
                ('receiver_phone', models.CharField(max_length=20, verbose_name='收货电话')),
                ('receiver_address', models.CharField(max_length=500, verbose_name='收货地址')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='订单备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名称（快照）')),
                ('product_image', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品图片（快照）')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价（快照）')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='订单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartItems', to='products.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartItems', to='users.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'cart_items',
                'indexes': [models.Index(fields=['user'], name='cart_items_user_id_2651f6_idx')],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='orders_user_id_4e08b8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_no'], name='orders_order_n_a26108_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status_762191_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_created_77e2b9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['receiver_phone'], name='orders_receive_3767b5_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='order_items_order_i_26ad88_idx'),
        ),
    ]
