# Generated by Django 6.0.1 on 2026-01-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password_hash', models.CharField(max_length=255, verbose_name='密码哈希')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='真实姓名')),
                ('status', models.IntegerField(default=1, help_text='1-正常, 0-禁用', verbose_name='状态')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员',
                'db_table': 'admins',
                'indexes': [models.Index(fields=['username'], name='admins_usernam_fc3a6f_idx'), models.Index(fields=['status'], name='admins_status_4ec923_idx')],
            },
        ),
    ]
