# Generated by Django 6.0.1 on 2026-01-13 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password_hash', models.CharField(max_length=255, verbose_name='密码哈希')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称')),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像URL')),
                ('status', models.IntegerField(default=1, help_text='1-正常, 0-禁用', verbose_name='状态')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
                'indexes': [models.Index(fields=['username'], name='users_usernam_baeb4b_idx'), models.Index(fields=['status'], name='users_status_9ca66f_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=50, verbose_name='收货人姓名')),
                ('receiver_phone', models.CharField(max_length=20, verbose_name='收货人电话')),
                ('province', models.CharField(max_length=50, verbose_name='省份')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('district', models.CharField(max_length=50, verbose_name='区县')),
                ('address', models.CharField(max_length=255, verbose_name='详细地址')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='邮编')),
                ('is_default', models.IntegerField(default=0, help_text='0-否, 1-是', verbose_name='是否默认地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
                'db_table': 'user_addresses',
                'indexes': [models.Index(fields=['user'], name='user_addres_user_id_0ee5d5_idx')],
            },
        ),
    ]
